version: "3.7"

services:
  Equipeservice:
    image: adamchibani/adamchibani-5twin4-g6-kaddem:kaddemimage
    restart: always
    depends_on:
      - mysql
    ports:
      - 8089:8089
    environment:
      - spring.datasource.url=jdbc:mysql://mysql:3306/kaddem?createDatabaseIfNotExist=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root

  mysql:
      container_name: mysql
      image: mysql
      restart: always
      volumes:
        - db:/var/lib/mysql
      ports:
        - 3306:3306
      environment:
        MYSQL_DATABASE: kaddem
        MYSQL_ROOT_PASSWORD: root

volumes:
  db: